apiVersion: v1
kind: ConfigMap
metadata:
  name: config-upf-configmap
  namespace: default
data:
  config.yaml: |
    pfcp:
      addr: "192.168.3.175"
      nodeID: "192.168.3.175"
      retransTimeout: 1s
      maxRetrans: 3
    gtpu:
      forwarder: "wmnsk/go-gtp"
      tunInterfaceName: upf
      ifList:
        - addr: "192.168.3.142"
          type: N3
    dnnList:
      - dnn: "internet"
        cidr: "10.60.0.0/16"
    logger: 
      level: "TRACE"
